name: Twitch CI

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'
# Um workflow é composto de um ou mais Jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este Workflow contém dois Jobs chamados "test"
  test:
    name: Check Code and Tests
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest  
    # Steps representam a sequencia de tarefas usando o shell runners que serão executadas como parte do Job
    steps:
    - uses: actions/checkout@v1
    #  Step para instalar o NDK
    - name: set Up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    #  Step para rodar testes unitários
    - name: Unit tests
      run: ./gradlew test --stacktrace
    # Check with Warnings
    - name: Check Warnings
      run: ./gradlew check --warning-mode all
    #Run Espresso Tests
    - name: Espresso Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 27
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        profile: pixel_3a
        script: ./gradlew connectedCheck